name: Ramification
favicon: null
layout_spectrum: 0.5132439145818353
typography_spectrum: 0.4592090172227472
title: Ramification.fr
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0f120b'
    - '#bdc1c0'
    - '#2f5814'
    - '#5a992f'
  brandStrength: 0.75
  lightness: 0.7977271783165634
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
